module.exports = {
  'TransferError': undefined,
  'LastResortAddressNotSet': undefined,
  'RecoveryAddressUpdated': undefined,
  'PaymentReceived': undefined,
  'PaymentSent': undefined,
  'PaymentForwarded': undefined,
  'AutoRecoveryTriggered': undefined,
  'AutoRecoveryTriggeredPrematurely': undefined,
  'RecoveryFailure': undefined,
  'RecoveryTriggered': undefined,
  'Retired': undefined,
  'ForwardAddressUpdated': undefined,
  'ForwardAddressAlreadySet': undefined,
  'ForwardAddressInvalid': undefined,
  'BackLinkUpdated': undefined,
  'BackLinkUpdateError': undefined,
  'ExternalCallCompleted': undefined,
  'ExternalCallFailed': undefined,
  'BackLinkAltered': undefined,
  'InvalidBackLinkIndex': undefined,
  'CommandDispatched': undefined,
  'CommandFailed': undefined,
  'DomainRegistered': undefined,
  'ReverseDomainClaimed': undefined,
  'ReverseDomainClaimError': undefined,
  'InvalidFQDN': undefined,
  'DomainRegistrationFailed': undefined,
  'AttemptRegistration': undefined,
  'DomainTransferFailed': undefined,
  'AttemptRenewal': undefined,
  'DomainRenewalFailed': undefined,
  'DomainTransferred': undefined,
  'DomainRenewed': undefined,
  'SignatureMismatch': undefined,
  'SignatureNotExist': undefined,
  'SignatureAlreadyExist': undefined,
  'SignatureAuthorized': undefined,
  'SignatureRevoked': undefined,
  'SignatureExpired': undefined,
  'ExceedSpendingLimit': { type: 'error', message: 'Aborted: spending limit exceeded', abort: true },
  'InsufficientFund': { type: 'error', message: 'Aborted: insufficient funds', abort: true },
  'ReceivedToken': undefined,
  'ForwardedToken': undefined,
  'TokenTransferFailed': undefined,
  'TokenTransferError': undefined,
  'TokenTransferSucceeded': undefined,
  'TokenRecovered': undefined,
  'BalanceRetrievalError': undefined,
  'TokenTracked': undefined,
  'TokenUntracked': undefined,
  'TokenNotFound': undefined,
  'CoreDisplaced': { type: 'success', message: 'Renewal / Restore complete!' },
  'CoreDisplacementFailed': { type: 'error', message: 'Renewal / Restore failed', abort: true },
  'ONEWalletDeployFailed': undefined,
  'ONEWalletDeploySuccess': undefined,
  'SpendingLimitChanged': undefined,
  'HighestSpendingLimitChanged': undefined,
  'SpendingLimitChangeFailed': { type: 'error', message: 'Failed to change spend limit', abort: true },
  'SpendingLimitJumped': undefined,
  'StakingSuccess': { type: 'success', messageTemplate: '{{sa:0}} succeeded (amount: {{amount}})' },
  'StakingFailure': { type: 'error', messageTemplate: '{{sa:0}} failed (amount: {{amount}})' }
}
